export interface IReportLiabilitiesData {
  accountCode: string
  name: string
  currency: string
  saldoNominal: number
  saldoEquival: number
  day7SaldoNominal: number
  day7SaldoEquival: number
  month1SaldoNominal: number
  month1SaldoEquival: number
  month2SaldoNominal: number
  month2SaldoEquival: number
  month3SaldoNominal: number
  month3SaldoEquival: number
  month4SaldoNominal: number
  month4SaldoEquival: number
  month5SaldoNominal: number
  month5SaldoEquival: number
  month6SaldoNominal: number
  month6SaldoEquival: number
  month7SaldoNominal: number
  month7SaldoEquival: number
  month8SaldoNominal: number
  month8SaldoEquival: number
  month9SaldoNominal: number
  month9SaldoEquival: number
  month10SaldoNominal: number
  month10SaldoEquival: number
  month11SaldoNominal: number
  month11SaldoEquival: number
  month12SaldoNominal: number
  month12SaldoEquival: number
  between1_2YearNominal: number
  between1_2YearEquival: number
  great2YearNominal: number
  great2YearEquival: number
}
